export const colorsLevel = ["White", "Red", "Blue", "Green", "Orange", "Black"];

export const levels = [
  "Low Roller",
  "Gambler",
  "Spinner",
  "Card Shark",
  "High Roller",
  "Whale",
];

export const hikes = [
  [
    ["Muffins"],
    ["Kraft Loop"],
    ["Grand Staircase"],
    ["Guardian Angle"],
    ["Railroad Tunnels"],
    ["Bristlecone Trail"],
    ["Fossil Ridge"],
    ["Cowboy Cave"],
    ["Ash Canyon"],
    ["Valley Of Fire Yellow Spire"],
    ["China Ranch"],
    ["Liberty Bell Arch"],
    ["Ice Box Waterfall"],
    ["White Rock Springs Loop"],
    ["Landmine Loop"],
    ["Wilson's Pimple Loop"],
  ],
  [
    ["Cahedral Rock"],
    ["Fern Canyon"],
    ["Calico Tanks"],
    ["Mary Jane Falls"],
    ["Big Falls"],
    ["Kraft Moutain"],
    ["Red Cap - Turtle Head Jr"],
    ["Trail Canyon Saddle"],
    ["Fortification Hill"],
    ["Windy Peak Backside"],
    ["Britt's Loop"],
    ["Boot Boulder"],
    ["Valley Of Fire Africe Loop"],
    ["Valley Of Fire Top Of World Arch"],
    ["North Bowl Of Fire Raven's Balcony"],
    ["Seven Dry Falls & Cholla Forset"],
    ["Lone Palm"],
    ["Boulder City Red And Black Mountains"],
    ["Hollow Rock Backside"],
    ["Turlehead Peak"],
    ["Red Springs Traverse"],
    ["Seal Head Rock Loop"],
    ["Read Springs - Two Old Men"],
    ["Calico Side Door"],
    ["Blue Diamond Canyons"],
    ["Fence Post Peak"],
  ],
  [
    ["Raintree"],
    ["Hamblin Mountain"],
    ["Northshore Peak"],
    ["Gray Cap"],
    ["Bonanza Peak"],
    ["Hidden Peak"],
    ["Fletcher Peak"],
    ["Global Peak"],
    ["White Rock Springs"],
    ["Frenchman Mountain"],
    ["Cockscomb Peak"],
    ["East Peak"],
    ["Valley of Fire Sandstone High Point"],
    ["SBOF Anniversary"],
    ["Trail Canyon to Fletcher Canyon"],
    ["Calico Tanks Peaks I and II"],
    ["Shark Fin Loop"],
    ["Linda Brock Memorial Route"],
    ["Terrace Canyon"],
    ["Imagination Trench"],
    ["Grand Circle"],
    ["Calico - Bits and Pieces"],
    ["Calico - LBMR variant"],
    ["Calico Tanks - Ridge Route"],
    ["Calico - Lost and Found"],
  ],
  [
    ["Black Mountain"],
    ["Magic Mountain"],
    ["Crabby Appleton"],
    ["Turtle Peak Jr - Double Slot"],
    ["Mack's Peak"],
    ["Mummy's Toe"],
    ["Mummy's Nose"],
    ["Brownstone"],
    ["Oak Creek Overlook"],
    ["Gunsight Notch"],
    ["Juniper Peak"],
    ["Black Velvet Peak"],
    ["Burlap Buttress"],
    ["Kraft No Route"],
    ["Calico - Shark Fin"],
    ["I've Been Lost Here"],
    ["Pyramid Peak, Death Valley"],
  ],
  [
    ["McFarland Peak"],
    ["White Rock Hills Peak"],
    ["First Creek Peak"],
    ["Indecision Peak"],
    ["Goodman Peak"],
    ["Oak Peak"],
    ["Mack's Peak North"],
    ["Mescalito"],
    ["Eva's Tower"],
    ["Bridge Point"],
    ["Sisters"],
    ["North Peak"],
    ["Griffith Peak"],
    ["Terrace Peak"],
    ["Mummy Mountain"],
    ["Lee Peak"],
  ],
  [
    ["White Pinnacle"],
    ["Bridge Mountain"],
    ["Bridge Vista"],
    ["Holiday Peak"],
    ["Pine Creek"],
    ["Mt Wilson"],
    ["Rainbow Peak"],
    ["Lost Creek - Graffiti Traverse"],
    ["Ice Box Peak"],
    ["Mt Charleston"],
    ["Mummy's Chin"],
    ["Mummy's Forehead"],
    ["Mummy's Head Loop"],
    ["Bridge 360"],
    ["Mummy Head to Toe"],
    ["Bonanza Trail"],
    ["Telescope Peak, Death Valley"],
  ],
];
